accounts:
  - name: alice
    coins: ['20000token', '200000000stake']
  - name: bob
    coins: ['10000token', '100000000stake']
  - name: relayer
    address: cosmos1zwsmvlankkn24dd6xg428e3fxqvphck2lrxstv
    coins: ['20000token', '200000000stake']
validator:
  name: alice
  staked: '100000000stake'
client:
  vuex:
    path: 'vue/src/store'
  openapi:
    path: 'docs/static/openapi.yml'
faucet:
  name: bob
  coins: ['5token', '100000stake']
genesis:
  chain_id: 'x:0'
# host:
#   rpc: ':26659'
#   p2p: ':26658'
#   prof: ':6061'
#   grpc: ':9091'
#   api: ':1318'
#   frontend: ':8081'
#   dev-ui: ':12346'
