// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: xchain/bridge.proto

package types

import (
	fmt "fmt"
	_ "github.com/cosmos/cosmos-sdk/types"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type MsgBridgeRequest struct {
	Reciever    string `protobuf:"bytes,1,opt,name=reciever,proto3" json:"reciever,omitempty"`
	Amount      uint64 `protobuf:"varint,2,opt,name=amount,proto3" json:"amount,omitempty"`
	Fee         uint64 `protobuf:"varint,3,opt,name=fee,proto3" json:"fee,omitempty"`
	DestChainId uint32 `protobuf:"varint,4,opt,name=destChainId,proto3" json:"destChainId,omitempty"`
	Signer      string `protobuf:"bytes,5,opt,name=signer,proto3" json:"signer,omitempty"`
}

func (m *MsgBridgeRequest) Reset()         { *m = MsgBridgeRequest{} }
func (m *MsgBridgeRequest) String() string { return proto.CompactTextString(m) }
func (*MsgBridgeRequest) ProtoMessage()    {}
func (*MsgBridgeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_09332d965c275dfb, []int{0}
}
func (m *MsgBridgeRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgBridgeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgBridgeRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgBridgeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgBridgeRequest.Merge(m, src)
}
func (m *MsgBridgeRequest) XXX_Size() int {
	return m.Size()
}
func (m *MsgBridgeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgBridgeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_MsgBridgeRequest proto.InternalMessageInfo

func (m *MsgBridgeRequest) GetReciever() string {
	if m != nil {
		return m.Reciever
	}
	return ""
}

func (m *MsgBridgeRequest) GetAmount() uint64 {
	if m != nil {
		return m.Amount
	}
	return 0
}

func (m *MsgBridgeRequest) GetFee() uint64 {
	if m != nil {
		return m.Fee
	}
	return 0
}

func (m *MsgBridgeRequest) GetDestChainId() uint32 {
	if m != nil {
		return m.DestChainId
	}
	return 0
}

func (m *MsgBridgeRequest) GetSigner() string {
	if m != nil {
		return m.Signer
	}
	return ""
}

func init() {
	proto.RegisterType((*MsgBridgeRequest)(nil), "rosen_labs.xchain.xchain.MsgBridgeRequest")
}

func init() { proto.RegisterFile("xchain/bridge.proto", fileDescriptor_09332d965c275dfb) }

var fileDescriptor_09332d965c275dfb = []byte{
	// 267 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0x90, 0xc1, 0x4a, 0xc4, 0x30,
	0x14, 0x45, 0x27, 0xce, 0x38, 0x68, 0x44, 0x18, 0xaa, 0x48, 0xe8, 0x22, 0x14, 0x57, 0x05, 0xb1,
	0x61, 0xf0, 0x0f, 0x46, 0x5c, 0xb8, 0x70, 0xd3, 0xa5, 0x1b, 0x69, 0xda, 0x67, 0x26, 0x60, 0x9b,
	0x31, 0x2f, 0x1d, 0xc6, 0xbf, 0x10, 0xbf, 0xca, 0xe5, 0x2c, 0x5d, 0x4a, 0xfb, 0x23, 0x92, 0xb4,
	0x8a, 0xab, 0x9c, 0x7b, 0x43, 0x72, 0xdf, 0xbb, 0xf4, 0x6c, 0x57, 0xae, 0x0b, 0xdd, 0x08, 0x69,
	0x75, 0xa5, 0x20, 0xdb, 0x58, 0xe3, 0x4c, 0xc4, 0xac, 0x41, 0x68, 0x9e, 0x5e, 0x0a, 0x89, 0xd9,
	0x70, 0x3f, 0x1e, 0x31, 0x2f, 0x0d, 0xd6, 0x06, 0x85, 0x2c, 0x10, 0xc4, 0x76, 0x29, 0xc1, 0x15,
	0x4b, 0x51, 0x1a, 0xdd, 0x0c, 0x2f, 0xe3, 0x73, 0x65, 0x94, 0x09, 0x28, 0x3c, 0x0d, 0xee, 0xe5,
	0x07, 0xa1, 0x8b, 0x07, 0x54, 0xab, 0x90, 0x91, 0xc3, 0x6b, 0x0b, 0xe8, 0xa2, 0x98, 0x1e, 0x59,
	0x28, 0x35, 0x6c, 0xc1, 0x32, 0x92, 0x90, 0xf4, 0x38, 0xff, 0xd3, 0xd1, 0x05, 0x9d, 0x17, 0xb5,
	0x69, 0x1b, 0xc7, 0x0e, 0x12, 0x92, 0xce, 0xf2, 0x51, 0x45, 0x0b, 0x3a, 0x7d, 0x06, 0x60, 0xd3,
	0x60, 0x7a, 0x8c, 0x12, 0x7a, 0x52, 0x01, 0xba, 0x5b, 0x3f, 0xdd, 0x7d, 0xc5, 0x66, 0x09, 0x49,
	0x4f, 0xf3, 0xff, 0x96, 0xff, 0x0b, 0xb5, 0x6a, 0xc0, 0xb2, 0xc3, 0x90, 0x32, 0xaa, 0xd5, 0xdd,
	0x67, 0xc7, 0xc9, 0xbe, 0xe3, 0xe4, 0xbb, 0xe3, 0xe4, 0xbd, 0xe7, 0x93, 0x7d, 0xcf, 0x27, 0x5f,
	0x3d, 0x9f, 0x3c, 0x5e, 0x29, 0xed, 0xd6, 0xad, 0xcc, 0x4a, 0x53, 0x8b, 0xd0, 0xc4, 0xb5, 0x6f,
	0x42, 0x8c, 0x4d, 0xed, 0x7e, 0xc1, 0xbd, 0x6d, 0x00, 0xe5, 0x3c, 0xac, 0x78, 0xf3, 0x13, 0x00,
	0x00, 0xff, 0xff, 0x01, 0x1d, 0xeb, 0xd1, 0x49, 0x01, 0x00, 0x00,
}

func (m *MsgBridgeRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgBridgeRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgBridgeRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Signer) > 0 {
		i -= len(m.Signer)
		copy(dAtA[i:], m.Signer)
		i = encodeVarintBridge(dAtA, i, uint64(len(m.Signer)))
		i--
		dAtA[i] = 0x2a
	}
	if m.DestChainId != 0 {
		i = encodeVarintBridge(dAtA, i, uint64(m.DestChainId))
		i--
		dAtA[i] = 0x20
	}
	if m.Fee != 0 {
		i = encodeVarintBridge(dAtA, i, uint64(m.Fee))
		i--
		dAtA[i] = 0x18
	}
	if m.Amount != 0 {
		i = encodeVarintBridge(dAtA, i, uint64(m.Amount))
		i--
		dAtA[i] = 0x10
	}
	if len(m.Reciever) > 0 {
		i -= len(m.Reciever)
		copy(dAtA[i:], m.Reciever)
		i = encodeVarintBridge(dAtA, i, uint64(len(m.Reciever)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintBridge(dAtA []byte, offset int, v uint64) int {
	offset -= sovBridge(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *MsgBridgeRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Reciever)
	if l > 0 {
		n += 1 + l + sovBridge(uint64(l))
	}
	if m.Amount != 0 {
		n += 1 + sovBridge(uint64(m.Amount))
	}
	if m.Fee != 0 {
		n += 1 + sovBridge(uint64(m.Fee))
	}
	if m.DestChainId != 0 {
		n += 1 + sovBridge(uint64(m.DestChainId))
	}
	l = len(m.Signer)
	if l > 0 {
		n += 1 + l + sovBridge(uint64(l))
	}
	return n
}

func sovBridge(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozBridge(x uint64) (n int) {
	return sovBridge(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *MsgBridgeRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowBridge
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgBridgeRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgBridgeRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Reciever", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBridge
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthBridge
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthBridge
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Reciever = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Amount", wireType)
			}
			m.Amount = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBridge
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Amount |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Fee", wireType)
			}
			m.Fee = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBridge
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Fee |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field DestChainId", wireType)
			}
			m.DestChainId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBridge
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.DestChainId |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Signer", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBridge
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthBridge
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthBridge
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Signer = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipBridge(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthBridge
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipBridge(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowBridge
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowBridge
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowBridge
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthBridge
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupBridge
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthBridge
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthBridge        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowBridge          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupBridge = fmt.Errorf("proto: unexpected end of group")
)
